"""empty message

Revision ID: 081d70b5edb0
Revises: 2f1279ef03ac
Create Date: 2021-01-26 18:28:52.589159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081d70b5edb0'
down_revision = '2f1279ef03ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_pokemon', sa.Column('base_exp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_pokemon', 'base_exp')
    # ### end Alembic commands ###
