"""empty message

Revision ID: 2f1279ef03ac
Revises: 0a513cffd548
Create Date: 2021-01-24 01:01:16.802804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1279ef03ac'
down_revision = '0a513cffd548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_pokemon', sa.Column('name', sa.String(length=40), nullable=True))
    op.add_column('trade_pokemon', sa.Column('sprite_url', sa.String(length=160), nullable=True))
    op.drop_column('trade_pokemon', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_pokemon', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('trade_pokemon', 'sprite_url')
    op.drop_column('trade_pokemon', 'name')
    # ### end Alembic commands ###
